### PR TITLE
Minify webmention.js. Refs #10

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

### CODE REVIEW

**Comment by fluffy-critter** [comment]
Looks good. I'm a little confused about why package-lock shows a version of 1.0.0 and package shows a version of 0.1.0, but I assume that's just A Thing.

Is this also enough to get it distributed in npm?

Thanks!

**Comment by Ryuno-Ki** [comment]
Oh, right. By default, `npm init --yes` creates a `1.0.0` version.
But I wasn't sure, considering #9.
Next time you increase the version via the CLI, it will sort itself out.

Check #9 for what's needed config wise. Perhaps also check the [docs on `npm publish`](https://docs.npmjs.com/cli/publish).

**Comment by fluffy-critter** [comment]
Thanks so much! You've been a great help. :)

**Comment by Ryuno-Ki** [comment]
You're welcome!
Let's [make Webmentions great](https://github.com/Ryuno-Ki/webmention-tools) together!

**Comment by fluffy-critter** [comment]
On that note, have you seen [Pushl](https://github.com/PlaidWeb/Pushl)? I was inspired by webmention-tools but wanted something a bit more automation-oriented.

**Comment by Ryuno-Ki** [comment]
No, I haven't.
If there's you would like to see webmention-tools do to make your job easier, let me know.
Right now I'm thinking in terms of CLI usage.
Perhaps support for django then next.

**Comment by fluffy-critter** [comment]
Ah, so, what Pushl does is it takes a feed of entries and automatically sends out the webmentions and websub notifications for everything, and can also track the differences so it only sends out updates. You can also use it to send webmentions for an individual entry, and optionally ask archive.org to crawl things you link to in case it disappears.

**Pull request merged**
